name: xray

on:
    push:
        branches: [main]
    workflow_dispatch:
        inputs:
            testPlanKey:
                description: "Test Plan ID from Xray"
                default: ""
                required: true
                type: string
            projectKey:
                description: "Project ID from Xray"
                default: ""
                required: true
                type: string
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        container:
            image: mcr.microsoft.com/playwright:v1.41.1-jammy
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run Playwright tests
              continue-on-error: true
              env:
                  HOME: /root
              run: |
                  npm run run:test
                  git config --global --add safe.directory /__w/Playwright_LamdaTest/Playwright_LamdaTest
            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  # ⚠️ enable playwright
                  playwright: true
                  # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  #   run: npm run chromatic
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
