name: xray
 
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      testExecKey:
        description: 'Test Exec ID from Xray'
        default: ''
        required: true
        type: string
      projectKey:
        description: 'Project ID from Xray'
        default: ''
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.41.1-jammy
    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Output Inputs
      run: echo "${{ toJSON(github.event.inputs) }}"
    - name: Get current working folder
      run: echo $PWD
    - name: Run tests
      continue-on-error: true
      env: 
        HOME: /root
      run: | 
        npx playwright test --grep '@only'
    - name: List all file in current directory 
      run: |
        ls
    - name: Output results file
      run: |
        cat results.xml
    - name: "Import results to Xray"
      uses: mikepenz/xray-action@v2.3.0
      with:
         username: C2C01C7147844FD2A79F7E1C4A71DF3A
         password: 15177a4619d2a83af195ef89f5e26a976e04f215d18a4f267407ae5abcb2720f
         testFormat: "junit"
         testPaths: "**/results.xml"
         testExecKey: "${{ inputs.testExecKey }}"
         projectKey: "${{ inputs.projectKey }}"
         testEnvironments: "NODE_${{ matrix.node-version }}"
